---
- hosts: all
  tasks:
    - name: Install and configure httpd web server
      when:  ansible_facts['distribution'] == 'CentOS'
      block:
        - yum:
            name: httpd
            state: present
        - service:
            name: httpd
            state: started
      rescue:
        - debug:
            msg: "Playbook has failed for {{ inventory_hostname }} node"
