----
- name: Compress multiple files
  hosts: web1
  tasks:
    - archive:
        path:
          - /root/file.txt
          - /usr/local/share/file2.txt
          - /var/log/lastlog
        dest: /root/files.tar.bz2
        format: bz2
