---
- name: Deploy lamp stack application
  hosts: all
  become: yes
  tasks:
    - yum:
        name:
          - libselinux-python
          - libsemanage-python
          - firewalld
        state: installed

- name: Configure lamp-db
  hosts: lamp-db
  become: yes
  tasks:
    - name: Install packages
      yum:
        name: 
          - mariadb-server
          - MySQL-python
        state: installed
    
    - name: Copy MySQL config file
      copy:
        src: files/my.cnf
        dest: /etc/my.cnf
        
    - name: Start mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
        
    - name: Start firewalld service
      service:
        name: firewalld
        state: started
        enabled: yes
        
    - name: Insert firewalld rule
      firewalld:
        port: 3306/tcp
        zone: public
        permanent: yes
        immediate: yes
        state: enabled

    - name: Create Application Database
      mysql_db:
        name: "{{ dbname }}"
        state: present
        
    - name: Create Application Database User
      mysql_user:
        name: "{{ dbuser }}"
        password: "{{ dbpassword }}"
        host: 172.20.1.100
        priv: "*.*:ALL"
        state: present
        
    - name: Copy db Script
      copy:
        src: files/db-load-script.sql
        dest: /tmp
        
    - name: Load Inventory Data from db script
      shell: "mysql -f < /tmp/db-load-script.sql"
