---
- name: Deploy lamp stack application
  hosts: all
  become: yes
  tasks:
    - yum:
        name:
          - libselinux-python
          - libsemanage-python
          - firewalld
        state: installed

- name: Configure lamp-db
  hosts: lamp-db
  become: yes
  tasks:
    - name: Install packages
      yum:
        name: 
          - mariadb-server
          - MySQL-python
        state: installed
    
    - name: Copy MySQL config file
      template:
        src: templates/my.cnf.j2
        dest: /etc/my.cnf
        
    - name: Start mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
        
    - name: Start firewalld service
      service:
        name: firewalld
        state: started
        enabled: yes
        
    - name: Insert firewalld rule
      firewalld:
        port: 3306/tcp
        zone: public
        permanent: yes
        immediate: yes
        state: enabled

    - name: Create Application Database
      mysql_db:
        name: "{{ dbname }}"
        state: present
        
    - name: Create Application Database User
      mysql_user:
        name: "{{ dbuser }}"
        password: "{{ dbpassword }}"
        host: {{ hostvars['lamp-web']['ansible_host'] }}
        priv: "*.*:ALL"
        state: present
        
    - name: Copy db Script
      template:
        src: templates/db-load-script.sql.j2
        dest: /tmp
        
    - name: Load Inventory Data from db script
      shell: "mysql -f < /tmp/db-load-script.sql"

- name: Install web service on lamp-web
  hosts: lamp-web
  become: yes
  tasks:
    - name: Install Web Server packages
      yum:
        name:
          - httpd
          - php
          - php-mysql
          - git
        state: installed
    
    - name: Start firewalld service
      service:
        name: firewalld
        state: started
        enabled: yes
        
    - name: Insert firewalld rule for httpd
      firewalld:
        port: "{{ httpd_port }}/tcp"
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
        
    - name: Set index.php as the default page
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "DirectoryIndex index.html"
        replace: "DirectoryIndex index.php"

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: yes
        
    - name: Clone the repo
      git:
        repo: "{{ repository }}"
        dest: /var/www/html/
        
    - name: Copy custom index.php
      template:
        src: templates/index.php.j2
        dest: /var/www/html/index.php
