---
- hosts: all
  tasks:
    - name: create group
      group:
        name: 'admin'
        state: present
        
    - name: create user
      user:
        name: 'admin
        uid: 2048
        group: 'admin'
