---
- name: Install httpd
  hosts: all
  strategy: free
  # to make the playbook run on one server at a time:
  # serial: 1
  gather_facts: no
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
        
    - name: start service
      service:
        name: httpd
        state: started
