---
- name: Install httpd
  hosts: all
  strategy: free
  gather_facts: no
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
        
    - name: start service
      service:
        name: httpd
        state: started
